###---------------------------------------------------------------LOGIN-------------------------------------------------------------------------------
### Request desde el formulario de logueo en el front
POST http://localhost:3000/auth
Content-Type: application/json

    {
        "usuario": "juan123",
        "password": "password1"
    }









###---------------------------------------------------------------USUARIOS--------------------------------------------------------------------------

### Obtencion de todos los Usuarios
GET http://localhost:3000/usuarios/


### Obtención de un Usuario especifico por su ID (solo usuarios nivel 3)
GET http://localhost:3000/usuarios/10/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjksInVzdWFyaW8iOiJqdWFuMTIzIiwiZXhwIjoxNjk4NjgxNDg5NzgzLCJpYXQiOjE2OTg2ODE0Mjl9.P_Dpkalduky7YxIq-aaX4wQsUfwYr6dtNmPUN-dZe94

### Agregar un nuevo Usuario (sin autorizacion por token para poder logearse por promera vez)
POST http://localhost:3000/usuarios/
Content-Type: application/json

{
    "nombres": "Nuevo Usuario",
		"apellidos": "apellido usuario",
    "dni": "12345678",
    "correo": "nuevo@usuario.com",
    "telefono": "+1 123-456-7890",
		"nivel": 1,
		"password": "1234",
		"usuario": "usuario123"
}

### Modificar atributo de usuario (debe ser usuario nivel 1, 2 o 3)
PATCH http://localhost:3000/usuarios/6
Content-Type: application/json
Authorization: Bearer

{
    "nombres": "nuevo nombre"
}

### Borrado de un usuario (debe ser usuario nivel 3)
DELETE http://localhost:3000/usuarios/5
Authorization: Bearer






###---------------------------------------------------------------PRODUCTOS---------------------------------------------------------------------------

### Obtencion de todos los productos (acceso sin token)
GET http://localhost:3000/productos/

### Obtención de un producto específico (acceso sin token)
GET http://localhost:3000/productos/32/

### Agregado de un producto nuevo (debe ser usuario nivel 3)
POST http://localhost:3000/productos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjExLCJ1c3VhcmlvIjoicGVkcm83ODkiLCJuaXZlbCI6MywiZXhwIjoxNjk4Njg3MjgwMjA2LCJpYXQiOjE2OTg2ODY2ODB9.ew0xq4Ew_QolETttLiza48hqEyEbBmli4TkEiCFFphU

{
  "nombre": "Monitor 144Hz",
  "descripcion": "Monitor gamer marca LG",
  "precio": "320.00",
  "stock": 5,
  "categoria_id": 1,
  "imagen_url": "Monitor.jpg"
}

### Actualización de un producto, el body lleva solo el atributo a modificar (usuarios nivel 3)
PATCH http://localhost:3000/productos/33
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjksInVzdWFyaW8iOiJqdWFuMTIzIiwibml2ZWwiOjEsImV4cCI6MTY5ODY4NzM1MTI0NiwiaWF0IjoxNjk4Njg2NzUxfQ.NVKf8IwsngjHpjnpnEjVZ9iyz952-tCUsZO4zvDMWlk

{
    "precio": "350.00"
}

### Borrado de un producto (usuario nivel 3)
DELETE http://localhost:3000/productos/32
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjExLCJ1c3VhcmlvIjoicGVkcm83ODkiLCJuaXZlbCI6MywiZXhwIjoxNjk4Njg2ODczMzQ0LCJpYXQiOjE2OTg2ODYyNzN9.YTefS74r0MybrjzgW0KaDICZ92yEHgVy6yNIBK_qG8c






###------------------------------------------------------ CATEGORIAS -----------------------------------------------------------------

###Obtención de todas las Categorías (acceso sin token)
GET http://localhost:3000/categorias/

###Obtención de una Categoría específica por su ID (acceso sin token)
GET http://localhost:3000/categorias/11/

###Agregar una nueva Categoría (usuario nivel 3)
POST http://localhost:3000/categorias/
Content-Type: application/json
Authorization: Bearer

{
  "nombre": "Nueva Categoría"
}
###Actualización de una Categoría, el body lleva solo el atributo a modificar (nivel 3)
PATCH http://localhost:3000/categorias/11
Content-Type: application/json
Authorization: Bearer

{
    "nombre": "Nueva Categoría Modificada"
}
###Borrado de una Categoría (nivel 3 - para borrar la categoría no deben haber productos asociados)
DELETE http://localhost:3000/categorias/11
Authorization: Bearer





###------------------------------------------------------------------ CARRITO -------------------------------------------------------------------------

### AGREGAR PRODUCTO AL CARRITO DE UN USUARIO, SI ES EL MISMO PRODUCTO SE MODIFICA SOLO LA CANTIDAD, MODIFICA EL STOCK EN LA BASE DE DATOS Y VERIFICA LA EXISTENCIA DE LA CANTIDAD DE PRODUCTOS (debe ser usuario nivel 1)
POST http://localhost:3000/carrito/9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjksInVzdWFyaW8iOiJqdWFuMTIzIiwibml2ZWwiOjEsImV4cCI6MTY5ODc2NzM3NTMzNiwiaWF0IjoxNjk4NzY2Nzc1fQ.9Le2w8vKZocrrp4y7jbt920l8x7Bl6GWVQaqOm38uWY

{
	"producto_id": 26,
  "cantidad": 50
}

### VER CONTENIDO DEL CARRITO DE UN USUARIO (debe ser nivel 1 o 3)
GET http://localhost:3000/carrito/9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjksInVzdWFyaW8iOiJqdWFuMTIzIiwibml2ZWwiOjEsImV4cCI6MTY5ODc3MjA4NDYzMSwiaWF0IjoxNjk4NzcxNDg0fQ.EWVVrUqAVyOtcqAlNYkVrnzCmSekuyjc9Yt-XQEzh_o

### eliminar productos del carrito de un usuario (nivel 1 y 3) (se debe colocar primero en la ruta el id del usuario y despues el id del producto a eliminar) (AL REALIZAR ESTA ACCIÓN SE MODIFICA EL STOCK DE LA BASE DE DATOS AGREGANDO NUEVAMENTE LOS PRODUCTOS ELIMINADOS)
DELETE http://localhost:3000/carrito/9/26
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjksInVzdWFyaW8iOiJqdWFuMTIzIiwibml2ZWwiOjEsImV4cCI6MTY5ODc2NzgzNjI3NywiaWF0IjoxNjk4NzY3MjM2fQ.GXIodcfriKXsLuALbe5Ubn7YB6jdWQbHpiXPKVEDeyY


###-----------------------------------------------------VENTAS-----------------------------------------------------------

### GENERAR UNA VENTA DE UN USUARIO QUE YA TENGA UN CARRITO CREADO (al crear la venta se elimina automaticamente el carrito creado - debe coincidir en la ruta y el body json el id del usuario ) (usuarios nivel 1)
POST http://localhost:3000/ventas/9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjksInVzdWFyaW8iOiJqdWFuMTIzIiwibml2ZWwiOjEsImV4cCI6MTY5ODc3MjA4NDYzMSwiaWF0IjoxNjk4NzcxNDg0fQ.EWVVrUqAVyOtcqAlNYkVrnzCmSekuyjc9Yt-XQEzh_o

{
    "usuario_id": 9
}

