### Obtencion de todos los productos
GET http://localhost:3000/productos/

### Obtención de un producto específico

GET http://localhost:3000/productos/26/

### Agregado de un producto nuevo, el body lleva el json con el objeto
POST http://localhost:3000/productos
Content-Type: application/json

{
  "nombre": "Tv smart",
  "descripcion": "Excelente tv smart 4k",
  "precio": "300.00",
  "stock": 9,
  "categoria_id": 2,
  "imagen_url": "tvSmart.jpg"
}

### Actualización de un producto, el body lleva solo el atributo a modificar

PATCH http://localhost:3000/productos/31
Content-Type: application/json

{
    "precio": "350.00"
}

### Borrado de un producto
DELETE http://localhost:3000/productos/8





### Obtencion de todos los Usuarios
GET http://localhost:3000/usuarios/

### Obtención de un Usuario especifico por su ID
GET http://localhost:3000/usuarios/3/

### Agregar un nuevo Usuario
POST http://localhost:3000/usuarios/
Content-Type: application/json

{
    "nombres": "Nuevo Usuario",
		"apellidos": "apellido usuario",
    "dni": "12345678",
    "correo": "nuevo@usuario.com",
    "telefono": "+1 123-456-7890",
		"rol": "cliente",
		"contrasena": "1234"
}

### Modificar atributo de usuario
PATCH http://localhost:3000/usuarios/6
Content-Type: application/json

{
    "nombres": "nuevo nombre"
}

### Borrado de un usuario
DELETE http://localhost:3000/usuarios/6


###--------------------------------------------- CATEGORIAS ----------------------------------------------
###Obtención de todas las Categorías
GET http://localhost:3000/categorias/

###Obtención de una Categoría específica por su ID
GET http://localhost:3000/categorias/11/

###Agregar una nueva Categoría
POST http://localhost:3000/categorias/
Content-Type: application/json

{
  "nombre": "Nueva Categoría"
}
###Actualización de una Categoría, el body lleva solo el atributo a modificar
PATCH http://localhost:3000/categorias/11
Content-Type: application/json

{
    "nombre": "Nueva Categoría Modificada"
}
###Borrado de una Categoría
DELETE http://localhost:3000/categorias/12

